BROKEN: minimal fucked case, cannot build
└[~/axhxrx-nx-esm-fuckery]> nx build nx-buildable-esbuild-lib

> nx run nx-buildable-esbuild-lib:build

The project nx-buildable-esbuild-lib is using the 'generatePackageJson' option which is deprecated for library projects. It should only be used for applications.
For libraries, configure the project to use the '@nx/dependency-checks' ESLint rule instead (https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks).
libs/nx-buildable-esbuild-lib/src/lib/Animal.ts:1:22 - error TS2307: Cannot find module '@axhxrx/date' or its corresponding type declarations.
  There are types at '/home/protiev/axhxrx-nx-esm-fuckery/node_modules/@axhxrx/date/_dist/mod.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

> 1 | import * as mod from "@axhxrx/date";
    |                      ^
  2 |
  3 | export class Animal
  4 | {

Found 1 error.

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target build for project nx-buildable-esbuild-lib (487ms)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

┌[protiev@fed-40-container] [/dev/pts/9] [main ⚡] [1]
└[~/axhxrx-nx-esm-fuckery]>