fix: Add workaround for Nx playwright config ESM incompatibility
But then LOL i am on Fedora, so Playwright still doesn't work... (unrelated to ESM stuff tho)

└[~/axhxrx-nx-esm-fuckery]> nx e2e angular-app-e2e

> nx run angular-app-e2e:e2e

> playwright test

ReferenceError: __filename is not defined in ES module scope
    at file:///home/protiev/axhxrx-nx-esm-fuckery/apps/angular-app-e2e/playwright.config.ts:19:18
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at requireOrImport (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/playwright/lib/transform/transform.js:191:26)
    at loadUserConfig (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/playwright/lib/common/configLoader.js:96:46)
    at loadConfig (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/playwright/lib/common/configLoader.js:101:22)
    at loadConfigFromFileRestartIfNeeded (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/playwright/lib/common/configLoader.js:258:10)
    at runTests (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/playwright/lib/program.js:191:18)
    at t.<anonymous> (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/playwright/lib/program.js:54:7)
Warning: command "playwright test" exited with non-zero status code
——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target e2e for project angular-app-e2e (406ms)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

┌[protiev@fed-40-container] [/dev/pts/10] [main] [1]
└[~/axhxrx-nx-esm-fuckery]> nx e2e angular-app-e2e

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

┌[protiev@fed-40-container] [/dev/pts/10] [main ⚡]
└[~/axhxrx-nx-esm-fuckery]> nx e2e angular-app-e2e --verbose

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  AggregateCreateNodesError: An error occurred while processing files for the @nx/playwright/plugin plugin.
    - apps/angular-app-e2e/playwright.config.ts: ENOENT: no such file or directory, lstat 'file:///home/protiev/axhxrx-nx-esm-fuckery/apps/angular-app-e2e/playwright.config.ts'
      at createNodesFromFiles (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/nx/src/project-graph/plugins/utils.js:58:15)
      at Array.exports.createNodesV2 (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/@nx/playwright/src/plugins/plugin.js:29:20)
      at LoadedNxPlugin.createNodes (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/nx/src/project-graph/plugins/internal-api.js:31:36)
      at LoadedNxPlugin.createNodes.<computed> (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/nx/src/project-graph/plugins/internal-api.js:41:28)
      at async Promise.all (index 3)
      at processFilesAndCreateAndSerializeProjectGraph (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:148:43)
      at Timeout._onTimeout (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:85:13)

┌[protiev@fed-40-container] [/dev/pts/10] [main ⚡]
└[~/axhxrx-nx-esm-fuckery]> nx e2e angular-app-e2e --verbose

> nx run angular-app-e2e:e2e

> playwright test

Running 3 tests using 3 workers
  1) [webkit] › example.spec.ts:3:1 › has title ────────────────────────────────────────────────────

    Error: browserType.launch: Executable doesn't exist at /home/protiev/.cache/ms-playwright/webkit-2003/pw_run.sh
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝

  2) [firefox] › example.spec.ts:3:1 › has title ───────────────────────────────────────────────────

    Error: browserType.launch: Executable doesn't exist at /home/protiev/.cache/ms-playwright/firefox-1449/firefox/firefox
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝

  3) [chromium] › example.spec.ts:3:1 › has title ──────────────────────────────────────────────────

    Error: browserType.launch: Executable doesn't exist at /home/protiev/.cache/ms-playwright/chromium-1117/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝

  3 failed
    [chromium] › example.spec.ts:3:1 › has title ───────────────────────────────────────────────────
    [firefox] › example.spec.ts:3:1 › has title ────────────────────────────────────────────────────
    [webkit] › example.spec.ts:3:1 › has title ─────────────────────────────────────────────────────

  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.
^C%
┌[protiev@fed-40-container] [/dev/pts/10] [main ⚡] [130]
└[~/axhxrx-nx-esm-fuckery]> npx playwright install
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
Downloading Chromium 125.0.6422.26 (playwright build v1117) from https://playwright.azureedge.net/builds/chromium/1117/chromium-linux.zip
156.8 MiB [====================] 100% 0.0s
Chromium 125.0.6422.26 (playwright build v1117) downloaded to /home/protiev/.cache/ms-playwright/chromium-1117
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
Downloading FFMPEG playwright build v1009 from https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip
2.6 MiB [====================] 100% 0.0s
FFMPEG playwright build v1009 downloaded to /home/protiev/.cache/ms-playwright/ffmpeg-1009
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
Downloading Firefox 125.0.1 (playwright build v1449) from https://playwright.azureedge.net/builds/firefox/1449/firefox-ubuntu-20.04.zip
85.7 MiB [====================] 100% 0.0s
Firefox 125.0.1 (playwright build v1449) downloaded to /home/protiev/.cache/ms-playwright/firefox-1449
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
Downloading Webkit 17.4 (playwright build v2003) from https://playwright.azureedge.net/builds/webkit/2003/webkit-ubuntu-20.04.zip
131.9 MiB [====================] 100% 0.0s
Webkit 17.4 (playwright build v2003) downloaded to /home/protiev/.cache/ms-playwright/webkit-2003
Playwright Host validation warning:
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     sudo npx playwright install-deps                 ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     sudo apt-get install libnss3\                    ║
║         libnspr4\                                    ║
║         libdbus-1-3\                                 ║
║         libatk1.0-0\                                 ║
║         libatk-bridge2.0-0\                          ║
║         libcups2\                                    ║
║         libdrm2\                                     ║
║         libatspi2.0-0\                               ║
║         libx11-6\                                    ║
║         libxcomposite1\                              ║
║         libxdamage1\                                 ║
║         libxext6\                                    ║
║         libxfixes3\                                  ║
║         libxrandr2\                                  ║
║         libgbm1\                                     ║
║         libxcb1\                                     ║
║         libpango-1.0-0\                              ║
║         libcairo2\                                   ║
║         libasound2                                   ║
║                                                      ║
║ <3 Playwright Team                                   ║
╚══════════════════════════════════════════════════════╝
    at validateDependenciesLinux (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/playwright-core/lib/server/registry/dependencies.js:216:9)
    at async Registry._validateHostRequirements (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/playwright-core/lib/server/registry/index.js:603:43)
    at async Registry._validateHostRequirementsForExecutableIfNeeded (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/playwright-core/lib/server/registry/index.js:701:7)
    at async Registry.validateHostRequirementsForExecutablesIfNeeded (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/playwright-core/lib/server/registry/index.js:690:43)
    at async t.<anonymous> (/home/protiev/axhxrx-nx-esm-fuckery/node_modules/playwright-core/lib/cli/program.js:119:7)
┌[protiev@fed-40-container] [/dev/pts/10] [main ⚡]
└[~/axhxrx-nx-esm-fuckery]>
┌[protiev@fed-40-container] [/dev/pts/10] [main ⚡]
└[~/axhxrx-nx-esm-fuckery]>
┌[protiev@fed-40-container] [/dev/pts/10] [main ⚡]
└[~/axhxrx-nx-esm-fuckery]>
┌[protiev@fed-40-container] [/dev/pts/10] [main ⚡]
└[~/axhxrx-nx-esm-fuckery]> nx e2e angular-app-e2e --verbose

> nx run angular-app-e2e:e2e